apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: ghcr.io/riseaicloud/landing-page
    newTag: 19a39cce56bb424e27c1039b25ac881f2e388f67
