apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: ghcr.io/riseaicloud/landing-page
    newTag: f49004f98996a7eaa3d22028a29ccb5c6b72d221
