apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: ghcr.io/riseaicloud/landing-page
    newTag: 0b2b143a81d04a1bfc2945d5b9f5e0f8df428ee7
